language: go
go:
- 1.8.x
install:
- go get -v github.com/spf13/hugo
script:
- hugo
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: rprakashg-io-web
  upload-dir: blog
  local_dir: ~/gopath/src/github.com/rprakashg/blog/public
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: UMHf0otzbcAyMxOaBqTriiyyJ1cOSg8D2jZDzPyObEdQ/WeZ2JM9XHXNNIF8MQmUGURD4g3GqWGKUzsEkN/LQnu6ODbQhVF/NDKdyO+ubnexWO8gD77GUHJmBbcCxcVY9eX77mWZ/GtDfTrA06H5p3asLn6nwUaw5OLtme1hImgptHEWCsYwf4oKnyzRQQFW7+nf/8yLVCGPYvf+JfinJIel4oQvMo9SEgTv5Tz7QRBjGrhX7A1ZAkdrb7Db96UUj67ez1MTuMulFpIOXEjQIO8FBDPN5wGWx/XdT5XFLV6GI+vHxVZ9IHQwmRSJWIKnV2fQzw2N5RLPmnmrsbbpyp8oOSRGcNN0tAigCkL2BDKionRMe3kSVth4dmHlkGGnJJ6wlubuSgi0nCvFP9ia96kO7iMLJ2FgN5pJZD2LOjFcpmiWHz8E/KKtv/xuFjTBBm2K7gBmKEjtlatzusxwEvafedJ20ZknLd5iIbLVJzGKicj3KHk1MQQePlJFlTma8ITPosKoOyxsUsSw6Pqy1QEimmlP6L8FJMrj6yhbHkT6jed8oSQbjk/8RTLA08VdsWNKd9Wj0DW+xPL0kk2cQjOvs5HnSufN8fGmd3nUDSXct/vsLjVfMLCFSUBNXNeUTarrsyQjuqaJS5x+PQJ1iE5ZVm3SIXX3c0bKLZzKnHg=
  - secure: hhmS/6NyWBKYuHR/q/3+xzkswm0QMz8g61uGGkrVySd+nrbuCkHi1ufi91OR1LHTV7nXPUKS9DnhMwEhlURF1hnTTA3v59H05asKk/VkQ3mtykGRN5wiBYDzXJ9V7nhSp7Q0fqfSn6Y/q7KGvZuqttgZzCMu5V9g+T+rkmrniVxMNhLvv5t1SgJEnmiH+RQE+4ch6wHRV3uFRK76ht79Y3h/teB6qNmNzXt1CpM95lG4fV/izw1EVSvENnbIiByrgnaTVtL/nIPkwp1nXCZ4ZcUhLBnTMpxhlOerahRoi0ZSrC1qWovDvV8tNSnmyxkWR5rLMGYFVRJX67oUafKJB64pErfUZMGZ9+azfziuY6tk1kw+aNhYT8XHQmD9ZIV6R6u+ZCXiepWs2dWwqbqNtKPq2kEOHkWgBA3iY/DZ9AYT0BEf69JsWTsCR95uVpn+8kKuuwfcUJWuL/sjugR8qqaKgR2k02jESCbc2aV17O0GVfbVqVq6VSua7eGtVUWVojJkHRCYXPq/wBpuHoWzyi956PKgIXQQDHU3XuAjUMiIsz/CEU/W4dxXQ3+F82rOydWmc8jJt0X9iz9CiH5xHwtGYdxfU8heGSEJ+txyrvUD1BYVPEotMmJFTE+tlT/5Iyd/jRXcm+PUv4G+6fBxJdcO74nTKe0kNw56LQCQ//Y=
