---
title: "RPRAKASHG.GITHUB.IO"
languageCode: "en-us"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
    category: "categories"
baseurl: https://rprakashg.github.io/blog/
canonifyurls: true
permalinks:
  post: /:year/:month/:title/
enableEmoji: true
googleAnalytics: "UA-20393691-5"
disqusShortname: "rams-blog"
theme: "hugo-beg"
menu:
  main:
    - Name: "ABOUT"
      Pre: "<i class='fa fa-heart'></i>"
      Weight: -110
      Identifier: "about"
      URL: "/about/"
    - Name: "CONTACT"
      Pre: "<i class='fa fa-road'></i>"
      Weight: -100
      URL: "/contact/"
...